### ISSUE TITLE
Slider still scrollable at last slide

### ISSUE THREAD

**Issue by webkitvn** [metafizzy/flickity#1001]
Hi, I have a problem with my slider. When I click Next button to the last item, Slider still scrollable, the Next button just disappeared until I clicked 3 times.

You can test on my site: https://qpconcept.com/shop/phong-bep/tu-bep/tu-bep-chu-i/tu-bep-hien-dai-kieu-chu-i-tbi0018/

**Comment by XPOL555** [comment]
@webkitvn Try using https://flickity.metafizzy.co/options.html#groupcells

**Comment by nekooee** [comment]
I have the same problem but I don't want to use group cell. Because with each key, only one slide should go forward or backward. Also, I change contain to false, the first slide is placed in the middle at the beginning of the slider!, but I want it to be placed first. It also eats extra scrolls when it reaches the end. The next key should be disabled when the last slide enters the page. The index is not important to me at all. I don't know how to solve the problem.
