### ISSUE TITLE
Odd initial transform with cellAlign left and wrapAround

### ISSUE THREAD

**Issue by kapouer** [metafizzy/flickity#1016]
https://codepen.io/kapouer/pen/xxbopBJ
This pen shows the cells are oddly placed:
- first at left 300%
- second at left 100%
- third at left 200%

Compared to the case without cellAlign option:
- first at left 0%
- second at left 100%
- third at left 200%

As soon as the user moves the first cell, it moves back to the right position.

This is problematic for some other reason (interaction with external lazyloader, the second image cannot be preloaded even with rootMargin because it is too far away).

Thanks looking into this.

**Comment by kapouer** [comment]
Additional info:
```
var cellAlignShorthands = {
  // cell align, then based on origin side
  center: {
    left: 0.5,
    right: 0.5
  },
  left: {
    left: 0.001,
    right: 0.009
  },
  right: {
    right: 0,
    left: 1
  }
};
```
works around the issue, so the problem might be something like bad rounding.

**Comment by desandro** [comment]
Thanks for reporting this issue. This issue appears to be related to how the cell positioning is calculated. It's most apparent on the first selected cell. But otherwise, it behaves just fine. Given the low interest in this issue, I'm going to close this one as un-fixed.

**Comment by darkkatarsis** [comment]
@desandro Is it possible to consider reopen? When I try to use cellAlign and wrapAround together causing an "empty gallery" effect due to incorrect position of 1st image. After touching, it calculates correctly. It is not troublesome on the desktop, but on the mobile version it is.

Ps. This white blinking is a page reload

![ezgif-1-a59a80cef0](https://user-images.githubusercontent.com/24244919/164531440-fbf76638-90df-45c8-a8e8-c3cc6d2b21ff.gif)
d
