### ISSUE TITLE
Update option, setting with events 

### ISSUE THREAD

**Issue by sadeghbarati** [metafizzy/flickity#1029]
@desandro : |
**Test case:** https://codepen.io/riccardo051/pen/OJVbyZz

update option, setting with onClick button

for example for multilang website i need to change **rightToLeft** option to `true` of `false`
I just try every similar issues ! but still have problem

1. destroy and reinit with new options [sucks] => not good looking
2. carousel.options.rightToLeft = false [sucks] => not removing `flickity-rtl` class after call this in onClick and arrows are reverts

3.
``` javascript
var options = {
   rightToLeft = true
}

button.click(function() {
   options.rightToLeft = false
}) 

var carousel = new Flickity('.carousel' , options);

// initialized with rightToLeft true but can not change options on another event except matchMedia
```
var option and update object in var option and pass it to flickity is not working

**Comment by clarknelson** [comment]
shouldn't it be `var option = { rightToLeft: true };` ?

When the user switches between languages I would assume the user expects some changes. A hard HTTP request to a website running on another domain (en.example.com) is not out of the ordinary. I would recommend that you use one of these techniques instead of modifying the existing loading using AJAX. Even if you use the AJAX approach to change the page, it doesn't seem that strange if you need to re-build a gallery, since all the other text on the page is changing also. 

Maybe i'm missing something but I feel that your best option would be to re-create the gallery with the desired options based on the multicultural settings.

**Comment by riiccardo** [comment]
it's a sample @clarknelson not real code 

but i test it's not working

**Comment by riiccardo** [comment]
https://glidejs.com/docs/options/

with glide can change options at once.

not just with `matchMedia`

**Comment by desandro** [comment]
> destroy and reinit with new options [sucks] => not good looking

I recommend this approach for the time being.
