### ISSUE TITLE
gallery don't loads on initial page load rather i have to refresh web page again and then it loads 

### ISSUE THREAD

**Issue by ZulqurnainHaneef** [metafizzy/flickity#1066]
**Test case:** https://codepen.io/desandro/pen/azqbop

I am using a gallery of flickity on my webpage and from chrome browser when you visit this page 
https://somewherecrazy.com/morocco-marrakech/
Gallery won't load then if you make the page to refresh a second time then it loads and only on chrome I am facing this issue. My chrome version is (Version 83.0.4103.61 (Official Build) (64-bit))

Thanks for such a nice plugin

**Comment by JordanSayner** [comment]
Have you tried using the imagesLoaded and lazyLoad settings? check them out here - https://flickity.metafizzy.co/options.html#images

**Comment by MikeyJN** [comment]
It's probably because you are initialising the carousel via HTML and therefore it's firing before the page is fully ready. Instead try initialising with jQuery and wrapping it with 'ready' so it only fires once the page has loaded.

so firstly in your HTML replace:

`<div class="carousel" data-flickity>`

with:

`<div class="carousel">`

and now add the following jQuery:

```
$(document).ready() {
$('.main-carousel').flickity({
    // options
    cellAlign: 'left',
    contain: true
});
});
```

Mike

**Comment by c-a-d** [comment]
I had the same issue even with `imagesLoaded: true`.

It seems to me that this issue appears when flickity calculates the height of the carousel to the height of the tallest cell (the code behind the `setGallerySize` option).

My solution: I forced the carousel to resize once loaded using the `resize` method (see https://flickity.metafizzy.co/api.html#resize) and the problem seems to be solved.

**Comment by daerentis** [comment]
I realized that I **initialized it twice** with the `data-flickity` attribute **and** with jQuery.
Removing the `data-flickity` attribute solved the problem. Yay!

**Comment by c-a-d** [comment]
@daerentis : are you sure your post concerns this issue? My carousel does not have the `data-flickity` attribute.

@eveybody: after 2 weeks on a production website, I confirm forcing the carousel to resize once loaded fixed the problem for me.

**Comment by phervind** [comment]
The solution from Chat GPT working well for me 

```javascript
document.addEventListener('DOMContentLoaded', function() {
  var elem = document.querySelector('.carousel');
  var flkty = new Flickity(elem, {
    // Flickity options
    // ...
  });
});
```

In this example, the DOMContentLoaded event is used to wait for the entire HTML document to be loaded before executing the code inside the event listener. The .carousel selector targets the element that contains your carousel content. Make sure to replace .carousel with the appropriate selector for your specific HTML structure.

Within the event listener, the Flickity initialization code creates a new instance of Flickity using the new Flickity() constructor. You can provide additional options for Flickity as needed.

By wrapping the Flickity initialization code within the DOMContentLoaded event, you ensure that the content is ready before Flickity is initialized, which may help resolve the issue you are experiencing.
