### ISSUE TITLE
Select next slide easily

### ISSUE THREAD

**Issue by Jack-Bailey** [metafizzy/flickity#1172]
I've only been learning HTML + CSS for a couple weeks so I might just be missing something simple but I'm trying to create a scrolling system where the middle slide has more details - I've done this part with selecting but I'd like it to be the next one after the one that's selected, and hopefully work with wrapping around too.
I made a [codepen](https://codepen.io/jackbailey/pen/eYWRaKR) to demonstrate this

So when Project 1 is selected, Project 2 will highlight magenta, and when Project five is selected, Project 1 will highlight.

Thanks!

**Comment by ethanjohnstone** [comment]
There is a chance you've already solved this but in case:

Does changing your Flickity definition to the following cover your case? 
data-flickity='{"cellAlign": "center", "contain": true, "wrapAround": true }'

This sets the selected slide to be the middle slide rather than the left aligned like your example.

**Comment by desandro** [comment]
[You have to add some code with the change event](https://flickity.metafizzy.co/events.html#change
)
