### ISSUE TITLE
v2.3.0 broke my carrousel

### ISSUE THREAD

**Issue by MTulaimat** [metafizzy/flickity#1195]
images not loading 

I just set a specific version and it worked **v2.2.2**

![image](https://user-images.githubusercontent.com/23016689/146744194-a5731dbb-f0fe-4d30-803b-3d4246cd1a16.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case** or a live URL so I can take a look? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by ianhobbs** [comment]
Broke mine as well. I have fixed height settings. https://alanschacher.net/work2.php?s=performature-performateur-3

**Comment by desandro** [comment]
@ianhobbs Thanks for that. Looks like we need to set `top: 0` now that Flickity uses transforms.

Can you try adding this code before you initialize Flickity?

```js
let protoCreate = Flickity.Cell.prototype.create;
Flickity.Cell.prototype.create = function() {
  protoCreate.apply( this, arguments );
  this.element.style.top = 0;
};
```

**Comment by ianhobbs** [comment]
Thanks for your quick reply - will report on changes when they are in.

**Comment by ryancanzo** [comment]
Hi @desandro, I have a similar issue. Since v2.3.0, the inactive cells overlap into the viewport. The translateX value of the 'flickity-slider' element increments at irregular values such as 100.41%, 200.82% etc which is the cause of the gap.

I was unable to reproduce the issue in CodePen but you can see the live url here: https://architextures.org/pro. I would appreciate any suggestions you may have to remove these gaps and overlaps.

![flickity](https://user-images.githubusercontent.com/7273861/147246952-f4d3f744-45a1-4fd7-b598-e8a3c9046e21.jpg)

**Comment by alexbogias** [comment]
Same here

**Comment by desandro** [comment]
This issue has been quiet for a year. I'm closing for now.
