### ISSUE TITLE
Validity of generated code

### ISSUE THREAD

**Issue by marcamos** [metafizzy/flickity#124]
Hello! I don't *believe* this particular ~~issue~~ question warrants a reduced test case, but correct me if I'm wrong and I'll set one up quickly.

Simply: when my pre-Flickity'ed markup starts its life as an unordered list, the Flickity-generated markup is then invalid: the `<li>`s are plopped into `<div>`s. Here's an example, borrowed from my [company's website](http://fromtheoutfit.com):

```html
<ul class="testimonials-list custom-underlines--light-bg flickity-enabled is-draggable" tabindex="0">
  <div class="flickity-viewport" style="height: 390px;">
    <div class="flickity-slider" style="left: 0px; transform: translateX(0%);">
      <li class="testimonial is-selected" style="position: absolute; left: 0%;">
        ...stuff...
      </li>
      <li class="testimonial" style="position: absolute; left: 101.2%;">
        ...stuff...
      </li>
      <li class="testimonial" style="position: absolute; left: 202.4%;">
        ...stuff...
      </li>
      <li class="testimonial" style="position: absolute; left: 303.6%;">
        ...stuff...
      </li>
      <li class="testimonial" style="position: absolute; left: 404.8%;">
        ...stuff...
      </li>
      <li class="testimonial" style="position: absolute; left: 506%;">
        ...stuff...
      </li>
    </div>
  </div>
  <button class="flickity-prev-next-button previous" type="button">
    <svg viewBox="0 0 100 100"><path d="M 50,0 L 60,10 L 20,50 L 60,90 L 50,100 L 0,50 Z" class="arrow" transform="translate(15,0)"></path></svg>
  </button>
  <button class="flickity-prev-next-button next" type="button">
    <svg viewBox="0 0 100 100"><path d="M 50,0 L 60,10 L 20,50 L 60,90 L 50,100 L 0,50 Z" class="arrow" transform="translate(85,100) rotate(180)"></path></svg>
  </button>
</ul>
```

I imagine that an acceptable solution might be: don't use an unordered list, but instead a series of `<div>`s … but then I'd lose some nice semantics.

Any thoughts? This is hardly a big issue, I'm just wondering if you've thought about it and if your proposed solution would be what I wrote above.

Thanks for your hard work!

**Comment by desandro** [comment]
Thanks for reporting this issue. While Flickity's generated markup may technically invalidate your HTML, I don't feel it prevents you from doing anything. One solution would be to re-write the new markup is generated, wrapping new elements around previous ones, rather than inserting them. But this feels like more work worth the benefits of "valid" HTML.

Bottom line for me: won't fix. But if more people chirp up about it, I'm happy to reconsider.

**Comment by marcamos** [comment]
![Sounds good](http://marcamos.com/ha/i-approve.gif)

**Comment by tedw** [comment]
@desandro I’m concerned about the accessibility implications of this. I tested with VoiceOver and it says there are only 3 items—presumably the “flickity-viewport” div and prev/next buttons—instead of the actual number of list items. I’m guessing the other major screen readers behave similarly. Fixing this would allow folks to use your awesome script on sites that require strict a11y compliance 😄 

If updating the code to avoid breaking lists is too much of a lift, perhaps you add `role="list"` and `role="listitem"` to the appropriate elements:

```html
<div class="flickity-slider" role="list" style="…">
  <div class="carousel-cell is-selected" role="listitem" style="…"></div>
  <div class="carousel-cell" role="listitem" style="…"></div>
  <div class="carousel-cell" role="listitem" style="…"></div>
  <div class="carousel-cell" role="listitem" style="…"></div>
  <div class="carousel-cell" role="listitem" style="…"></div>
</div>
```

The only downside of this is that developers would have to use divs, which means the source code wouldn’t be accessible without JS.

We _could_ add the roles to the source code, but you would still need to tweak the JS to move the `role="list"` from the outer wrapper to the “flickity-slider” wrapper. Here’s a demo http://codepen.io/tedw/pen/ORpYpj?editors=1000

Anyway, big fan of yours, keep up the great work! 👍

**Comment by desandro** [comment]
@tedw Thanks for your expertise here.
