### ISSUE TITLE
"asNavFor"

### ISSUE THREAD

**Issue by lexbi** [metafizzy/flickity#13]
Hi Guys,

Looking good so far, though I'd like an "asNavFor" feature request like flexslider/slick have like this:

http://flexslider.woothemes.com/thumbnail-slider.html

**Comment by desandro** [comment]
Thanks for this request! This should be able to do with Flickity's API -- rather than build out an option for this.

If you would like to see this feature, please **+1** this ticket.

---

Thanks you for this feedback. [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), please email me yo@metafizzy so I can send some your way.

**Comment by lunelson** [comment]
+1

that's a pretty cool feature

**Comment by SRTM** [comment]
+1
A standard feature that every slider should have.

**Comment by lunelson** [comment]
Yeah it seems to me if the api provides the right methods, callbacks etc. it should be pretty straightforward to use one to navigate another, maybe this just needs a little tutorial

**Comment by lexbi** [comment]
Maybe it should just be an option though, rather than offering a little tutorial. Especially if this plugin isn't even going to be free.

**Comment by pavethiran** [comment]
+1
maybe as addon

**Comment by desandro** [comment]
[`asNavFor` is now implemented in Flickity](http://flickity.metafizzy.co/options.html#asnavfor) v0.2.3. Closing as fixed :white_check_mark:
