### ISSUE TITLE
it doesn't read jquery call

### ISSUE THREAD

**Issue by spostad7** [metafizzy/flickity#16]
hi
first of all I have to tanx for your brilliant work. I removed all my previous slider plugins and start to use this as soon as I found it!
but I have an issue, when I call the plugin from js file, it seems the slider did not read the js and it run itself without any js Initialization! I find it out when I changed some options and I noticed that none of them were activated. it run with default option with no jquery call!
what is happening!!? 
heres my html:
```
<div class="slideshow js-flickity" data-flickity-options='{ "autoPlay": 3500, "freeScroll": true, "pageDots": false, "wrapAround": true }'>
    <div class="gallery-cell"><img src="img/slide1.jpg" alt="" /></div>
    <div class="gallery-cell"><img src="img/slide2.jpg" alt="" /></div>
</div>
```

I had to run my options through html, but I want to call them from js file.
Tanx

**Comment by desandro** [comment]
It sounds like you need to remove `js-flickity` class when you are initializing Flickity with jQuery.

---

To initialize with HTML, add `js-flickity` class and set options in `data-flickity-options`. Your example code should work just fine.

``` html
<div class="slideshow js-flickity"
  data-flickity-options='{ "autoPlay": 3500, "freeScroll": true, "pageDots": false, "wrapAround": true }'>
    <div class="gallery-cell">...</div>
    <div class="gallery-cell">...</div>
</div>
```

To initialize with jQuery, remove `js-flickity` class and `data-flickity-options` from your HTML

``` html
<div class="slideshow">
  <div class="gallery-cell">...</div>
  <div class="gallery-cell">...</div>
</div>
```

``` js
$('.slideshow').flickity({
  autoPlay: 3500,
  freeScroll: true,
  pageDots: false,
  wrapAround: true
});
```

---

Thanks you for this feedback. [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), email me yo@metafizzy so I can send some your way.

**Comment by spostad7** [comment]
tanx for your reply. it was totally helpful. 
I missunderstood the "watchCss" option and when I used it, everything messed up. I just removed it and also remove js-flickity and it perfectly worked fine for me.
tanx again

**Comment by lilianchen** [comment]
Hey there!
Just stumbled across this thread trying to get my Flickity to initialize through jQuery. It totally works, though I have run into the previous poster's concern: watchCSS (true or false) breaks thing in Safari. It works swimmingly in Chrome! By "breaks", it's as if the script was never even initiated. Broken at all screen sizes (since I am using this with queries).

Another thing I've noticed is that setting the gallery-cell's height to auto works great in Chrome, allows for resize, but in Safari renders at around 5px tall. Figured I'd shoot these issues your way in case you had any insight.

Thanks for the incredible resource! Really hoping I can get this working for my personal site :].


~ Lil

**Comment by desandro** [comment]
@lilianchen Sup Milktea! Thanks for reporting your difficulty. To help clear up the issue, can you open a new issue with a **reduced test case** demonstrating the issues? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by lilianchen** [comment]
@desandro Ha! Hi there! I just jumped into making a reduced case and LO AND BEHOLD, all it turned out to be another script for my responsive navigation that was clashing with it! I'm still new to the Git world, would you prefer I ask here or create a new topic?

(You saved me hours of nitpicking CSS!)

**Comment by davidhellmann** [comment]
I've the same Issue @lilianchen :/
Chrome alle fine but Safari / Firefox all broken. Looks like no init is fired. When I resize the browser it worked. strange :(
