### ISSUE TITLE
Lazyloading background images

### ISSUE THREAD

**Issue by nicholas-c** [metafizzy/flickity#173]
Hey, so I'm using flickity which is amazing however want to lazy-load background images for a slide in. No <img> tags being used per slide.

I've forked my own version and changed flickity.pkgd.js and was going to PR however wanted to open this for discussion first;

Changes I've made.
Adding to getCellLazyImages - 

``` js
|| cellElem.nodeName == 'DIV' && cellElem.getAttribute('data-flickity-lazyload')
```

when checking cells. Alongside

``` js
  if(imgs.length < 1) {
    var imgs = cellElem.querySelectorAll('div[data-flickity-lazyload]');
  }
```

Finally where it loads the image: 

``` js
  // load image
  if(this.img.nodeName == 'DIV') {
    this.img.style.backgroundImage = 'url("' + this.img.getAttribute('data-flickity-lazyload') + '")';
  } else {
    this.img.src = this.img.getAttribute('data-flickity-lazyload');
  }
```

Thoughts?

**Comment by desandro** [comment]
Thanks for this feature request. **+1** if you would like to see lazy load background images added to Flickity proper. This could be a useful feature. I'd like to gauge other's interest before we merge it in.

You generally have the right idea. One issue is that a proxy image will have to be used to detect when the image has loaded.

**Comment by ksherman** [comment]
+1 for sure! background-size: cover is super useful in responsive design with images, so this would be super helpful.

**Comment by nicholas-c** [comment]
@desandro - I'll work on a PR and get it to you later today :)

**Comment by hi-im-si** [comment]
+1

**Comment by nicholas-c** [comment]
PR opened - https://github.com/metafizzy/flickity/pull/174

**Comment by impsart** [comment]
+1

**Comment by danielflodin** [comment]
+1

**Comment by JourneyRoss** [comment]
+1

**Comment by richgcook** [comment]
+1

**Comment by nathankleyn** [comment]
+1 from me too!

**Comment by EugeneDae** [comment]
+1

**Comment by nlfonseca** [comment]
+1

**Comment by drala** [comment]
+1

**Comment by aaronstezycki** [comment]
+1

**Comment by Jinksi** [comment]
+1

**Comment by romanenko** [comment]
+1

**Comment by lmartins** [comment]
+1 for lazy loading background images

**Comment by nonlinearcom** [comment]
+1

**Comment by Chriz74** [comment]
+1

**Comment by JustasKuizinas** [comment]
+1

**Comment by mikedidthis** [comment]
+1

**Comment by mikkeltschentscher** [comment]
+1

**Comment by davidetamburini** [comment]
+1

**Comment by driera** [comment]
This feature would be great!!

**Comment by igregson** [comment]
+1

**Comment by kostyasys** [comment]
+1

**Comment by benjasHu** [comment]
+1

**Comment by desandro** [comment]
Thanks all for your feedback. I have built this feature and will be releasing it with Flickity v2, in the next month.

**Comment by nfq** [comment]
+1

**Comment by kostyasys** [comment]
any news?

**Comment by na86** [comment]
+1

**Comment by desandro** [comment]
I've released [`flickity-bg-lazyload`](https://github.com/metafizzy/flickity-bg-lazyload) for Flickity v2, an add-on library that enables [`bgLazyLoad` option](http://flickity.metafizzy.co/options.html#bglazyload). [See demo on CodePen](http://codepen.io/desandro/pen/jAGAEb).

Set the background image's URL to load with `data-flickity-bg-lazyload`.

``` html
<div class="carousel">
  <div class="carousel-cell"
    data-flickity-bg-lazyload="tulip.jpg"></div>
  <div class="carousel-cell"
    data-flickity-bg-lazyload="breakfast.jpg"></div>
    ...
</div>
```

``` js
bgLazyLoad: true
// lazyloads background image in selected slide

bgLazyLoad: 1
// lazyloads background image in selected slide
// and next 1 cell
// and previous 1 cell
```

`flickity-bg-lazyloaded` is not included in Flickity or `flickity.pkgd.js` files and [must be installed separately](https://github.com/metafizzy/flickity-bg-lazyload#install).

This issue is now closed :tada: [Open a new issue on the flickity-bg-lazyload repo](https://github.com/metafizzy/flickity-bg-lazyload/issues) if you run into any issues with `bgLazyLoad`. Thank you for all the feedback and your patience. Glad to finally ship this one :blush:

**Comment by Rok-fullstack** [comment]
Hi there!

I have one question, how to set different background image for mobile/tablet and still be lazyloaded? Because if I set different image in css for mobile, the desktop background image is still loadded so it takes some additionally time to load the page.

Do you have any suggestions on how to fix this?
