### ISSUE TITLE
previous & next arrows do not move slider when multiple cells visible

### ISSUE THREAD

**Issue by luchebert** [metafizzy/flickity#177]
Hi, this is more of a help question (possible feature request) but I've got various galleries setup with Flickity that have a wide container, but some of them only have 2-3 cells (items) in them (aligned left) so at that point I don't require the PrevNext arrows to show up since the cells are all displayed with plenty of room width to spare, but in this case the Next arrow shows up anyway and does nothing since the container is much wider than the cells, once I click the Next arrow, the Prev arrow shows up as well and also does nothing.

Any thoughts, advice or help would be appreciated! Thanks!

**Comment by desandro** [comment]
Hi! Thanks for this feature request. I get what you're asking for. When multiple cells are visible or with `'contain': true`, there can be areas when clicking the previous/next arrows won't move the slider. Here's a demo: http://codepen.io/desandro/pen/ZGrpLN

While the slider does not change, the selected cell does. This may be useful for accessibility, as it allows users to select a cell with buttons, rather than with mouse.

So your request is valid, but it's important to keep previous & next arrows working consistently for accessibility.

**Comment by luchebert** [comment]
Thanks for the info! That makes sense.

**Comment by splurtcake** [comment]
@desandro I see your point but I still feel like this is a bug.

For example if my carousel has 4 items, and shows 3 at a time, I need to click the "next" arrow 3 times before it becomes disabled... How can I get around this?

**Comment by desandro** [comment]
@splurtcake Try [groupCells](http://flickity.metafizzy.co/options.html#groupcells)
