### ISSUE TITLE
Disable swiping if less than n items in slider

### ISSUE THREAD

**Issue by alexhillel** [metafizzy/flickity#187]
I have a slider which shows 1 item in view (width 100%) on mobile, and 3 items in view (width 33.33%) on desktop. Is there anyway I can disable Flickity if there are less items in the slider than the number in view at a particular time?

If there are only two items in the slider on desktop, I would like to prevent swiping and hide the prev/next arrows and navigation dots, as swiping is unnecessary when there are less items than the slider displays.

**Comment by desandro** [comment]
Thanks for this question. I recommend using [`watchCSS`](http://flickity.metafizzy.co/options.html#watchcss) to handle this kind of behavior.

**Comment by alexhillel** [comment]
Thanks David. My concern with watchCSS is that it disables Flickity completely and thus loses the markup and styling provided by the plugin. Even if the item counting/disabling wasn't built into the core, it would be great if there were methods to enable/disable Flickity's swipe functionality and show/hide the UI elements, but keep it in a 'ready to go' state complete with it's provided markup and structure. Then I could manually tell it when to enable/disable.

**Comment by pandroid** [comment]
+1

This option would be great.  In a CMS elements are added dynamically.

Situation A:   3 elements in the gallery
Desktop-View -> element-width 33% -> flickery off
Tablet-View -> element-width 50% -> flickyery on, because 1 element is off the row
Mobile-View -> element-width 100% -> flickery off

Situation B: 4 elements in the gallery
Desktop-View -> element-width 33% -> flickery on, because 1 element is off the row
Tablet-View -> element-width 50% -> flickyery on, because 2 element are off the row
Mobile-View -> element-width 100% -> flickery off

Is it possible to check, if elements are out of the flickery container?

**Comment by pandroid** [comment]
Maybe there is a solution with a additional script?

If the sum of the widths of all child elements is greater than the width of the parent gallery container activate flickery (e.g. with a additional class).

**Comment by desandro** [comment]
See related feature request #278

**Comment by desandro** [comment]
Closing this issue. Please use #278 for discussion.
