### ISSUE TITLE
asNavFor with wrapAround on iOS native (not emulated) skipping cells

### ISSUE THREAD

**Issue by drastick** [metafizzy/flickity#189]
When clicking a thumbnail it skips cells and selects the wrong one.  This does not happen when emulating in chrome but does happen on an actual iOS device.  Tested on iOS 8.4 (phone) and 8.3 (tablet)

Test case:
http://codepen.io/synapen/pen/aOawxW

**Comment by desandro** [comment]
Thank you for reporting this bug. I'll have to investigate how to resolve this.

**Comment by desandro** [comment]
This bug is fixed in Flickity v1.1.1. [Try it out!](http://flickity.metafizzy.co/) :pear: 

The bug was caused by iOS's emulated click event that gets triggered 300ms after the tap. The fix involved listening for `mouseup` event after `staticClick` events and ignoring them.

Thanks again for reporting this bug!
