### ISSUE TITLE
Support CSS Scroll Snap Points

### ISSUE THREAD

**Issue by williambout** [metafizzy/flickity#251]
Feature request : Support CSS Scroll Snap Points
This feature is implemented in Safari (iOS 9 and El Capitan), Edge and Firefox. Currently in development in Chrome.

**Comment by desandro** [comment]
Thank you for this feature request. **+1 this issue** if you would like to see this feature added.

Scroll snap points are an interesting feature. If you're considering using them, you probably don't need Flickity anyway. Or, Flickity would need to be seriously re-tooled in order to support it. Currently Flickity uses transforms for positioning, as opposed to scroll positioning.

**Comment by benjamincharity** [comment]
:+1:

**Comment by desandro** [comment]
This feature request is similar to #130. Closing this one here so we can group it all there.
