### ISSUE TITLE
addEventHandlers on .flickity-prev-next-button doesn't work on iOs

### ISSUE THREAD

**Issue by matthieuc** [metafizzy/flickity#262]
Hi

great script, thank you

we use it in comination with an audio player, and I works great on desktop. on prev/next, the addEventHandlers stop the music and load the next track, so slides and sounds are linked

but on mobile, the linked function isn't used. do you know why ?

``` js
function addEventHandlers(){
   $(".flickity-prev-next-button").click(nextPrevAudio);
}
```
and the function
``` js
function nextPrevAudio(){
   var $gallery = $('.main-gallery');
   var flkty = $gallery.data('flickity');
   var cellNumber = flkty.selectedIndex;
  
		audio.trigger('pause');
		audio.empty();
		$( "<source src='"+src[cellNumber]+"'></source>" ).appendTo(audio);
		audio.trigger('load');
		$('#current').html('00:00');
		$('#duration').html('00:00');

}
```

event if I put a simple alert('ok'); in the function, it doesn't work on mobile

you can check here : http://nathanielmechaly.bienavous-dev.net/cinema/grandmaster

thank you for your help

**Comment by desandro** [comment]
Thanks for reporting this issue! The prev/next buttons are [tap listeners](https://github.com/metafizzy/tap-listener). These react immediately to tap events, rather than waiting for emulated `click` events on touch devices. As you reported, `click` event listeners on touch devices will not work.

You can use the tap events instead. See demo http://codepen.io/desandro/pen/EVXRjK

``` js
var $gallery = $('.gallery').flickity();
// get Flickity instance
var flkty = $gallery.data('flickity');

// bind tap listeners
flkty.prevButton.on( 'tap', function() {
  console.log('prev button tapped')
});

flkty.nextButton.on( 'tap', function() {
  console.log('next button tapped')
});
```

**Comment by matthieuc** [comment]
thank you desandro, it works! perfect
