### ISSUE TITLE
"Non-Flickity" Items

### ISSUE THREAD

**Issue by zslabs** [metafizzy/flickity#264]
Hi,
I'm attempting to integrate items within a Flickity instance with both slider items and "non" slider items. There's a very convenient `cellSelector` option we can use to isolate slider items, but if I try to integrate in non-slider items into this, I have to fudge the styles that are associated with the to line up with. Is there a way to "skip" items that are added within a Flickity?

Demo at http://codepen.io/zslabs/pen/BoQyRX

**Comment by zslabs** [comment]
http://codepen.io/zslabs/pen/GpEWYO That's what I was able to come up with so far -- basically creating a "clean list" of actual flickity items.

**Comment by desandro** [comment]
Thanks for reporting this issue. [`cellSelector`](http://flickity.metafizzy.co/options.html#cellselector) is useful if you have other kind of content within the carousel, like a banner. Your example is different as you're placing content in between the cells of the navigation gallery. This conflicts with Flickity's cell layout behavior.

Rather than use `asNavFor`, I recommend creating a your own [custom navigation](http://flickity.metafizzy.co/extras.html#custom-navigation-ui).

**Comment by zslabs** [comment]
Hey @desandro thanks for the hint on that - I think my second CodePen does that (kinda), but is a little different than the custom navigation example purely based on the specific needs of that thumbnail viewer below. I thought the way I created a "cleansed" nav list might be useful for others so they can still get the styling/calculation benefits of Flickity treating it as a normal cell, but with some checks on the element itself to determine how it should respond.
