### ISSUE TITLE
Does Flickity allow Isotope filtering within the slider?

### ISSUE THREAD

**Issue by mstopford442** [metafizzy/flickity#279]
Is this possible?
I'd like to be able to filter items within the flickity slider using the same way Isotope works.

**Comment by desandro** [comment]
Sorry, no it does not.

You can use Isotope to filter element within a cell. You can use Isotope to filter elements that use Flickity. See http://tympanus.net/Blueprints/FilterableProductGrid/ But you cannot filter slides within a Flickity carousel.

**Comment by mstopford442** [comment]
Ok, thanks for your response.
Is there any built in form of filtering within Flickity?

**Comment by desandro** [comment]
> Is there any built in form of filtering within Flickity?

No. You cannot filter Flickity cells.

**Comment by mstopford442** [comment]
Ok, I have a requirement for it in a project so I hope you don't mind if I add that functionality to it.

**Comment by jeffaglenn** [comment]
I know this is an old post but wanted share my solution in case others were looking for a way to filter the slides in a Flickity Slider. It doesn't use Isotope because I didn't need everything Isotope offers.

It basically adds and removes classes then destroys and inits Flickity when the filters are clicked.

https://codepen.io/jeffglenn/full/YYwMao
