### ISSUE TITLE
"Download flickity.pkgd.min.js" on the homepage links v1.1.2, but serves v1.1.1

### ISSUE THREAD

**Issue by EugeneDae** [metafizzy/flickity#323]
Is this a bug?

![screen shot 2016-02-10 at 14 31 49](https://cloud.githubusercontent.com/assets/980835/12946109/0e351a06-d003-11e5-9838-a90eb4b02616.png)

![dl](https://cloud.githubusercontent.com/assets/980835/12946084/dc08bbfa-d002-11e5-9b4b-1896b427e9da.png)

**Comment by desandro** [comment]
Thanks for reporting this issue! It's a clerical error on my part. `flickity.pkgd.js` v1.1.2 has the correct code, but the wrong version in its header comment. See SHA: 19b0b4ee41450949ce91bb86e685739c3841c7fe for fix commit. I haven't published a new release since then, so this error is still present.

**Comment by desandro** [comment]
Flickity v1.2.0 has been released and properly displays `v1.2.0`. Closing as fixed :bear:
