### ISSUE TITLE
Collapse on Window resize

### ISSUE THREAD

**Issue by TimDHolley** [metafizzy/flickity#38]
Having an issue with my flickity collapsing and the height being adjusted to ridiculous numbers when I resize my window.  Here is a link to check it out,  http://79.170.44.98/saublesmartsolutions.com/

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like the problem is with how `#partsstretch { float: left; }`. Because it's a float, it will collapse its width to its content. Flickity works by inheriting its width from its parent. So when you resize it, there's no 'stable' size on either end thus the collapse. Adding `width: 100%; ` or removing `float: left` on `#partsstretch` seems to fix this.

**Comment by TimDHolley** [comment]
Perfect, thanks for the fix.
