### ISSUE TITLE
pop images when clicked

### ISSUE THREAD

**Issue by afrocomb101** [metafizzy/flickity#380]
Would it be possible to make images pop into a larger size hovering in the center of the page when clicked? Thank you.

**Comment by desandro** [comment]
Yes, this is possible. But as to how to do it, I'll leave that up to you.  You might want to use CSS or jQuery. Flickity re-uses your HTML. So try creating this effect _without_ Flickity, then when you have something you like, add back Flickity to see how it looks.

This demo uses a fancy style for selected cells: http://codepen.io/desandro/pen/jEpxqJ/

**Comment by GemeenAapje** [comment]
Hi guys
I have the same question.

the problem is not making a popup work (I have that working fine on double-click), the problem is that single click is triggered constantly by swiping.
So each time you swipe left or right the popup is triggered as a single click.

The only solution I could make was changing to double-click for popup, but most people can't get used to this.

Any ideas?

Thanks
Matt

**Comment by desandro** [comment]
@GemeenAapje Use Flickity's [staticClick event](http://flickity.metafizzy.co/api.html#staticclick), rather than basic click event.

**Comment by GemeenAapje** [comment]
Thanks so much for the reply (only just seen it, sorry)!  I've now been trying to get the staticClick to work but it kills my entire gallery whenever I add the event handler in JS or Jquery.

I think the reason is because I'm using the HTML method of loading (no JS/Jquery).

Is it possible to add the StaticClick somehow to the cell (rather than jquery)?

Thanks again.
Matt
