### ISSUE TITLE
how to get rid of the gap?

### ISSUE THREAD

**Issue by am3000** [metafizzy/flickity#382]
Hey,

I´m having this problem with that gap on the right side of the most right image.
It seems that all is fine on the first load, but when you resize the browser window,
this gap turns up next to the "next" button.

http://codepen.io/Bolko/pen/jqjVjg

Any hint on how I can solve this?
If there were a little gap left AND right half as big as the right one is, it would be ok, but like this it doesn´t look good :(
a padding of 0.5% instead of the margin on -col-3-12 would solve it in the pen, but not in my real-world-website, as the columns have a background-color and it also don´t really make sense to have a padding here instead of a margin.

**Comment by desandro** [comment]
That gap on the right is the `0.5%` margin. If its not initially appearing, that may be because the scrollbar. Try adding `html { overflow-y: scroll; }` to see if behavior is more consistent after resizing window. cellAlign will align the content of the cell, excluding its initial margin. This aligns cells to the starting edge of the carousel.

Try:

+ setting `cellAlign: 'center'`
+ Use a different CSS instead of the `col-3-12`.

**Comment by am3000** [comment]
Hi desandro, thanks for your reply.
Yep, the gap is 0.5% margin-left PLUS 0.5% margin-right, so 1% alltogether. 
With `html { overflow-y: scroll; }` the behaviour is more consistent, so that the gap is there from the beginning, I hoped to find a way where to make the gap go away ;)

I finally hackfixed it with `.flickity-viewport {  margin-right:-0.5%; }`

**Comment by yumyo** [comment]
I am having the same problem when using `cellAlign` other than `center` . Is hadding a negative margin to `.flickity-viewport` the "official" fix for it?

**Comment by ifa-charlie** [comment]
html { overflow-y: scroll; } still works in June 2018.

**Comment by tsawitzki** [comment]
html { overflow-y: scroll; } still works in May 2021.
Hope there's a better setting for that soon.
