### ISSUE TITLE
Slides stuck on MS Surface, Windows Phone

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#410]
[Dave Allen](https://twitter.com/three60five/status/751463561226907648)

> Surface w/Edge and Windows Phone using flickity.metafizzy.co Slides getting stuck, not advancing smoothly

**Comment by fabrizim** [comment]
I'm working with Chrome on a Windows 10 touch screen and ran into similar issues. I found that the last call to final call applyDragForce with isPointerDown was yielding the x and dragX properties equal, especially when I tried to do make quick drags. My patch is to store the previous X position and check for equality:

`(function windowsFix(proto){
    var applyDragForce = proto.applyDragForce;
    var touchFix = function(){
      if( !this.isPointerDown ){
        this.previousX = null;
        return;
      }
      if( this.x === this.dragX && this.previousX && this.previousX !== this.dragX ){
        this.x = this.previousX;
      }
      this.previousX = this.x;
    };
    
    proto.applyDragForce = function(){
      touchFix.call(this);
      applyDragForce.call(this);
    };
  })(Flickity.prototype);`

I'm not sure if there are some existing properties that could be used (previousDragX), but this works for me for now. I was going to offer a pull request but I'm not sure if this type of thing should be added to unidragger or somewhere other than applyDragForce within Flickity.

**Comment by desandro** [comment]
Closing this one as it's been quiet for a while. Please chime in if you continue to run into this issue.

**Comment by metahub** [comment]
I am not sure if it 100%-ly fits here, but we are experiencing a similar sounding issue in Edge on Windows 10, too in a scenario when you have linked elements in your slider.

Example:

https://codepen.io/desandro/pen/vOeGzL

Chrome & Firefox work fine.
Edge using touchscreen works, too.

But dragging the slider in Edge with your mouse creates a really wonky experience, since the browser interprets the click and drag motion as a click on the clicked element, resulting the slider to permanently bind the clicked element to your mouse pointer which then moves the slider back and forth as you move your mouse around.

This only stops, when you finally click somewhere else on the page.

In the codepen example it actually works not as bad as in real life scenarios, since the images / links don´t fill the whole cells so that you can still drag normally if you don´t start on an image and if you did, you can click in the area that´s not filled by an image to reset.

But if your linked objects fill out the whole cell (like in product carousels etc.) you will always get that binding behaviour with every drag - and on a link heavy site you have nowhere else to click, to disconnect your cursor.

**Comment by desandro** [comment]
@metahub Thanks for reporting this. I'll have to take a look.
