### ISSUE TITLE
Keep the amount of is-selected cells consistent when using GroupCells on odd amounts

### ISSUE THREAD

**Issue by JesseHigson** [metafizzy/flickity#427]
When grouping an odd numbers of cells, it would be good to have the ability for the scroll amount to adjust to always keep the number of 'is-selected' cells consistent. 

For example if there are five cells grouped into threes rather than having the first group with a complete three and the second group with only two, the slider should only move the amount of the remaining cells ensuring that there are three 'is-selected' cells at all times.

http://codepen.io/anon/pen/akjkLr

**Comment by desandro** [comment]
Thank you for this feature request. I can see how this would be a nice behavior to add. However, I'm afraid it would require a large amount of code and complexity to make it work. There are other Flickity features, like `asNavFor`, that work well together because cells can only be in a single slide. I'm sorry, but I don't feel this feature is worth the extra complexity.

I appreciate your input on Flickity. Sorry to say not to this one
