### ISSUE TITLE
Having issues with staticClick, wrapAround and Previous and Next Links

### ISSUE THREAD

**Issue by DamirPecnik** [metafizzy/flickity#437]
Here is the CodePen example of what i am trying to do...
http://codepen.io/DamirPecnik/pen/YWdomJ

First the wrapAround (loop) when using the Next link and Previous link is not working good if the links are in the carousel-cell, i need that in the cell when it comes to 10 and then goes to 1 or vice versa it slides the whole carousel to come back to 1 or 10.

Second on staticClick i made it so when someone click the cell it adds a class is-clicked on the left cell of the centered one ( is-selected) this works good but i have an issue if you click on the number 10 cell more then once it slides the carousel one loop ...

**Comment by desandro** [comment]
Looks look both issues are happening because event handlers are interfering with one another. We can resolve this by using one event handler for clicks inside cells. You can also use `cellAlign` with decimals for custom position. This demo uses `cellAlign: 0.25`

http://codepen.io/desandro/pen/c9e1980e01c3f14e6a252a8121e8f408
