### ISSUE TITLE
Problem with slider height

### ISSUE THREAD

**Issue by fusi-sdm** [metafizzy/flickity#479]
Hi all,
i have a problem with slider and height.
If i initialize the slider in the document.ready, the slider will have height 0px the first time i load the page.
If i initialize the slider in window.load, it works but for an instance i will see all the slide in a column.

What is the best practice for that?

Thank you

**Comment by willpower232** [comment]
Presumably you would see all the slides in a column if the javascript fails to load so that is your starting point.

Ordinarily you would want all the slides to be visible for accessibility reasons.

However if you want the content to be hidden, I add a class of "unflickity" to the parent element of the slides which is **removed before flickity is activated** and has this CSS:

```CSS
.unflickity .slide:not(:first-child) {
	display:none;
}
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
