### ISSUE TITLE
Attaching click event listener selectively breaks .previous() and .next()

### ISSUE THREAD

**Issue by willpower232** [metafizzy/flickity#485]
Attaching a click event listener onto the carousel element breaks the movement of .previous() and .next() (i.e. from the flickity previous and next buttons) INSIDE the carousel element.

If you create previous and next buttons yourself INSIDE the carousel element, they are affected in a similar way.

If you create previous and next buttons yourself OUTSIDE the carousel element, they are not affected.

**Test case:** http://codepen.io/anon/pen/BQaJqG
(to replicate, click all previous and next buttons and note the unintended behaviour of the flickity previous and next buttons compared to the manual buttons)

**Comment by desandro** [comment]
Thanks for reporting this issue. Yes, the standard click event is problematic because dragging and releasing could be a click. That's why [Flickity has the `staticClick` event](http://flickity.metafizzy.co/events.html#staticclick). See demo http://codepen.io/desandro/pen/1a35ff049fbefa607e59d860c8d152a5

``` js
flkty.on( 'staticClick', function( event, pointer, cellElement, cellIndex ) {
  flkty.select( cellIndex );
});
```

**Comment by willpower232** [comment]
Perfect thank you!
