### ISSUE TITLE
Cannot set property element of undefined

### ISSUE THREAD

**Issue by jacobmischka** [metafizzy/flickity#487]
I could be doing something wrong, but I believe flickity is supposed to work with webpack without any additional configuration, but it doesn't seem to.

Error:
![image](https://cloud.githubusercontent.com/assets/3939997/20034829/99307d9c-a39a-11e6-88c3-fe6c01b37f1f.png)

Since I can't use a codepen to reproduce this, just clone this and `npm install && npm start` and open `index.html` in a browser: http://github.com/jacobmischka/flickity-webpack

Thanks!

**Comment by desandro** [comment]
Given that error, you are trying to initialize Flickity without a valid element.

``` js
var flkty = new Flickity( element, {...})
```

Double check that your `element` is in the page.

**Comment by jacobmischka** [comment]
If I'm not mistaken this is a different error than that. https://github.com/metafizzy/flickity/blob/master/js/flickity.js#L71

I've tried it with both an HTMLElement object I'm sure exists and a query selector string, and unless I'm just a complete idiot I'm pretty sure it exists in that example I linked.

`this` is what doesn't exist, not `element`. Im not sure what `this` is supposed to refer to, but I tried running Flickity = Flickity.bind({}) in case it just wants somewhere to keep things, but then it tried accessing `this.options` which hadn't  been assigned.

Thanks again!

**Comment by jacobmischka** [comment]
Actually, initializing the carousel with the `data-flickity` property in HTML is working for me. I haven't tried using jQuery, but I still haven't been able to get vanilla JS to work.

**Comment by desandro** [comment]
Looks like the code is missing the `new` keyword

``` js
var Flickity = require('flickity');

// add new
new Flickity('.carousel', {

});
```

**Comment by jacobmischka** [comment]
Oh ha I'm a moron. Thanks, sorry.

**Comment by sardug10** [comment]
Hey!!
I am trying to add the flickity elements under the 'main-carousel' div with insertAdjacentHtml, but those images are not going in a slideshow, rather they are stacking on top of each other. After that, I tried to insert the whole flickity element in the same manner but gain again I was getting the error probably because I was initializing the flickity before it appears on the page.
So, any method on how we can add elements in flickity when some data is coming from some API,
Please help me, I will be very thankful!!
