### ISSUE TITLE
gifs in iframe on Safari 

### ISSUE THREAD

**Issue by alexswider** [metafizzy/flickity#490]
We are having issue with safari iframe gifs. 

link here:
https://www.brigademarketing.com/portfolio/

video works fine,  gifs by themselves as well, but gifs in iframe are not playing, but if you try to resize the window it will jump to different frame of the gif :)

Let me know your thoughts.

**Comment by desandro** [comment]
Thanks for reporting this bug. I was not able to reproduce the issue using smaller GIFs, with no video. See demo https://jsfiddle.net/xn6nj9gk/. The issue is likely all the other media that is getting loaded. I recommend you only load images/video when cells are selected using the [`select` event](http://flickity.metafizzy.co/events.html#select)

**Comment by alexswider** [comment]
HI, here is updated example:
https://jsfiddle.net/xn6nj9gk/1/
doesn't works in Safari…
the issue is loading Iframe with gifs not gifs by themself

-- 
Alex Swiderski
Sent with Airmail

On November 17, 2016 at 7:48:01 AM, David DeSandro (notifications@github.com)
wrote:

Thanks for reporting this bug. I was not able to reproduce the issue using
smaller GIFs, with no video. See demo https://jsfiddle.net/xn6nj9gk/. The
issue is likely all the other media that is getting loaded. I recommend you
only load images/video when cells are selected using the select event
<http://flickity.metafizzy.co/events.html#select>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metafizzy/flickity/issues/490#issuecomment-261238291>,
or mute the thread
