### ISSUE TITLE
Autoplay issue?

### ISSUE THREAD

**Issue by samjudson** [metafizzy/flickity#5]
Hi

I was playing around with Flickity and Flickr, and came across a weird issue.

I was using JSFiddle, and sometimes would see a weird issue where the images where not laid out correctly when running. I have managed to reproduce this on every load of the full page now (F5 refresh) .

Here is the link to the JSFiddle: http://jsfiddle.net/samjudson/62qkb5eu/

Here is a screenshot of what it looks like when things go wrong: http://imgur.com/Ytn1NYE

Resizing the window, or clicking Run again and it works ok. Could be an issue with the frame not being loaded when Flickity runs perhaps, so the height information is off?

**Comment by desandro** [comment]
Hi! Thanks for submitting this bug. Looks like the problem is that the images need to load and have their size recognize by Flickity. You can do this with `imagesLoaded: true`. See example: http://jsfiddle.net/62qkb5eu/2/

I've documented the imagesLoaded option under **Images** in the beta docs.

---

Thanks for your help beta testing Flickity! Feel free to email me yo@metafizzy.co [if you'd like some stickers](http://metafizzy.co/blog/flickity-beta-testing/).

**Comment by samjudson** [comment]
Ah, thanks.
