### ISSUE TITLE
select event fires multiple times with lazyLoad

### ISSUE THREAD

**Issue by fireform** [metafizzy/flickity#504]
Hi David!
Thanks a lot for your huge work on this project!

I'm experiencing some odd behavior. So, I run two carousels (main + navigation). If I use "lazyLoad" option in the main carousel, "select" event triggers as many times as how many images specified to lazy load + first image + 1 additional firing (3 in total). I reproduced this on Codepen: http://codepen.io/wpspd/pen/GNzGdg As I understand, this shouldn't happen every time after lazy loading and, moreover, within the navigation. Now I need to use hacks to do not take into account false triggers. Is there any official workaround? Thanks in advance!

**Comment by chrisbraddock** [comment]
I just ran in to the same issue. I'm just going to try debouncing it for now.

**Comment by danimalweb** [comment]
Same issue here.

**Comment by desandro** [comment]
Thanks for reporting this issue.

For the record, this behavior is how Flickity is supposed to work — currently. When a cell's size changes, Flickity has to re-calculate the position of all the cells. Currently, it triggers `select` to resolve any position mismatch. I'll admit, it's clunky.

That said, I'm looking into refactoring this behavior. Using `select` feels like a hack in this case. If you're interested, [here's the relevant code](https://github.com/metafizzy/flickity/blob/v2.0.7/js/add-remove-cell.js#L156)

**Comment by hirasso** [comment]
I am having the same issue with `lazyLoad` firing many times when switching a cell (In my case I defined `lazyLoad: 2` and it's firing 5 times). Since I am manipulating the browser history on cell select, it always lags for a very short (but noticable) time. Of course I could go with the `settle` event, but I would prefer select for it's immediate response.

**Comment by desandro** [comment]
🎉  **[Flickity v2.1.0](https://github.com/metafizzy/flickity/releases/tag/v2.1.0) has been released with  all new [`change` event See docs!](https://flickity.metafizzy.co/events.html#change)** 🎉

> Triggered when the selected slide is changed.

``` js
// jQuery
$carousel.on( 'change.flickity', function( event, index ) {
  console.log( 'Slide changed to ' + index )
});

// vanilla JS
flkty.on( 'change', function( index ) {...});
```

`select` will continue to be triggered multiple times, but `change` is only triggered when the selected slide is changed. Use `change` to resolve the issue here.

I'm now closing this issue. Please open a new issue if you into trouble with using `change`. Thanks for sticking with Flickity! 🌈🐻
