### ISSUE TITLE
Add option to have a vertical slider rather than horizontal (feature suggestion)

### ISSUE THREAD

**Issue by benhuson** [metafizzy/flickity#508]
I like the `asNavFor` option and spotted the example in Extras of "Vertical scrollable navigation on the side".

Would be nice if you could create a vertical scroller like that using Flickity so that it can also be draggable and just use the `asNavFor` option.

:)

**Comment by desandro** [comment]
Thanks for this feature request. Sorry, but Flickity will not support a vertical slider. From https://github.com/metafizzy/flickity/issues/36#issuecomment-212905712

> Straight up: Flickity will never support vertical scrolling. It's too much code for too little benefit. Features like vertical thumbnail navigation do not have to be built into Flickity directly. You can leverage Flickity's well documented API and many demos to create these kind of add-on features.

**Comment by tristantbg** [comment]
Just a made a vertical mode if you want to try :
https://github.com/tristantbg/flickity

Options: 
`verticalCells: true`

**Comment by madshensel** [comment]
@tristantbg did you happen to make a demo of this in a codepen or similar?

**Comment by tristantbg** [comment]
@madshensel You can view it in action here : http://croandco.archi/projets/cnit

**Comment by Skoulix** [comment]
I'm not sure if the following example is the best approach but I made a pen that uses the built-in asNavFor option to make the thumbs carousel and then rotate and reposition everything with CSS. No javascript needed.

Check it out: https://codepen.io/Skoulix/full/LJyYEv/

**Comment by Julix91** [comment]
@tristantbg - I noticed you didn't make a pull request, right? I'm guessing because Desandro made clear it's not in his vision of Flickity?

@desandro - You keep saying how much code it would be to accommodate this... - Some conditionals here and there checking for whether the option exists and if so handling it slightly differently - is it really that big of a deal? Does increase risk for interaction effects and/or bugs?

You implemented `wrapAround` even though it's "potentially disorienting" because it's cool - and potentially awesome - and will get asked about. Vertical sliders have been asked about a lot.

Check out this for example I'm working on right now: 

![Screen Shot 2019-03-14 at 4 03 52 PM](https://user-images.githubusercontent.com/12877287/54397380-82bb3100-4673-11e9-8f50-3ad9818f3bb8.png)

infinite scrolling through the options (shouldn't be too many more than fit on the screen) 

On tablet that works well - on mobile it goes back to being a horizontal one (reduces scan-ability of items, but means we can "swoosh" through the images representing the tech in the same direction as the nav

The `overflow-y: scroll` solution doesn't work with wrapAround and doesn't always center the currently active item (like a gambling wheel would).

I'd take the above github branch and merge it into ours but I want to be able update to latest flickity version as needed without over-writing the changes... 

What do you suggest?

**Comment by Julix91** [comment]
@tristantbg - I noticed you didn't make a pull request, right? I'm guessing because Desandro made clear it's not in his vision of Flickity?

@desandro - You keep saying how much code it would be to accommodate this... - Some conditionals here and there checking for whether the option exists and if so handling it slightly differently - is it really that big of a deal? Does increase risk for interaction effects and/or bugs?

You implemented `wrapAround` even though it's "potentially disorienting" because it's cool - and potentially awesome - and will get asked about. Vertical sliders have been asked about a lot.

I'm currently working on something...

On the left
---
Tech 1
*Tech 2*
Tech 3
--- 

On the right
[visual representation of the currently active tech]

infinite scrolling through the options on the left with the active one always centred and its visual representation (say a robot) on the right.

On mobile the nav goes underneath and is horizontal again, to work well with the "swoosh" through the tech images...

The `overflow-y: scroll` solution doesn't work with wrapAround and doesn't always center the currently active item.

I'd take the above github branch solution and merge it into ours but I want to be able update to latest flickity version as needed without over-writing the changes... 

If I branch from current master, pull in the above feature, test it a bit and do a PR - any chance we could get it in? Is vertical too much work or against your vision even as an option?

**Comment by desandro** [comment]
@Julix91 Thanks for your thoughtful response.

>  Is vertical too much work or against your vision even as an option?

I realize it's a worthwhile feature that a lot of people ask for. But, in my experience, this is one of those features that is better left out. Adding vertical sliding to Flickity is absolutely do-able, but it comes at a high cost for complexity, for a feature that I don't feel that strongly about. Nor do I look forward to all the places in the code-base that need to be forked to account for vertical vs. horizontal positioning. For example, there's a lot of code accounting for vertical page scrolling. So I'm sticking with my guns on this one.

> If I branch from current master, pull in the above feature, test it a bit and do a PR - any chance we could get it in?

No, I will not merge the feature into Flickity master. However, you PR can act as a waypoint for people to find your fork.

**Comment by Julix91** [comment]
@desandro - thanks for explaining your position! 

Sounds like code complexity would increase more than I had realized.

**Comment by josefarrugia** [comment]
> I'm not sure if the following example is the best approach but I was playing and made a pen that uses the built-in asNavFor option to make the thumbs carousel and then rotate and reposition everything with CSS. No javascript needed.
> 
> Check it out: https://codepen.io/Skoulix/full/LJyYEv/

This greatly helped me! Probably the best answer here. Cheers! 👍🏼

**Comment by jonathan-dejong** [comment]
> I'm not sure if the following example is the best approach but I was playing and made a pen that uses the built-in asNavFor option to make the thumbs carousel and then rotate and reposition everything with CSS. No javascript needed.
> 
> Check it out: https://codepen.io/Skoulix/full/LJyYEv/

Can also confirm that this actually seem to work pretty good! Tweaked the layout a bit for my own purposes but the general solution is solid! 👍

**Comment by skoulix** [comment]
> The one thing I'd especially recommend is to set `cellAlign: 'left'` because otherwise if you only have one or a few nav items they'll end up vertically centered instead of top aligned (left being top in this case)

Yes, this seems a better option.
Thanks

**Comment by kylegoines** [comment]
> I'm not sure if the following example is the best approach but I was playing and made a pen that uses the built-in asNavFor option to make the thumbs carousel and then rotate and reposition everything with CSS. No javascript needed.
> 
> Check it out: https://codepen.io/Skoulix/full/LJyYEv/

this is amazing and works perfectly!

**Comment by dpw1** [comment]
The main issue with this approach is that it doesn't support dragging.

**Comment by dpw1** [comment]
> I'm not sure if the following example is the best approach but I was playing and made a pen that uses the built-in asNavFor option to make the thumbs carousel and then rotate and reposition everything with CSS. No javascript needed.
> 
> Check it out: https://codepen.io/Skoulix/full/LJyYEv/

Unfortunately it doesn't work with dragging on desktop, but other than that it's a good solution.

**Comment by decimate** [comment]
The CSS approach only seems to work with square thumbnails.

**Comment by dpw1** [comment]
> The CSS approach only seems to work with square thumbnails.

Do you mean it doesn't work with rectangles/circles?

**Comment by morgan-bluestone98** [comment]
Just my 2 cents, but after trying to get the above Codepen solution to work with my setup my advice is to just go with the Selecting Slides API. 10 minutes. Easy-peasy.

**Comment by skoulix** [comment]
> 

Hello, the above solution is already 3 years old if not more. If you have a nice solution please share with the world :-)
Take care.

**Comment by skoulix** [comment]
> Just my 2 cents, but after trying to get the above Codepen solution to work with my setup my advice is to just go with the Selecting Slides API. 10 minutes. Easy-peasy.

Hello, the above solution is already 3 years old if not more. If you have a nice solution please share with the world :-)
Take care.

**Comment by morgan-bluestone98** [comment]
To keep with your passive aggressive tone, yes, the solution is to use the Selecting Slides API which I mentioned in the original post.

Enjoy your week.

**Comment by atlamors** [comment]
I would like to add that vertical scrolling is an absolute essential use case for some best in class user experience solutions.
