### ISSUE TITLE
Pseudo elements on `.flickity-prev-next-button` do not trigger slide

### ISSUE THREAD

**Issue by amustill** [metafizzy/flickity#522]
When attempting to increase the hit area of the buttons via a pseudo element on `.flickity-prev-next-button`, clicking on the rendered pseudo does not trigger a slide.

**Test case:** http://codepen.io/anon/pen/VpweNP

I have included an example native button where the `click` event fires when clicking the pseudo.

This technique is useful when you want to increase the clickable area for smaller or touch devices.

**Comment by desandro** [comment]
Thanks for submitting this issue. Tap Listener is designed for multi-touch. So it has to check that the pointer is within the bounds of the element to consider it a click.

Instead of using a pseudo element, you can resize the button itself with CSS. Then resize the arrow with CSS. You can then use the pseudo element to create a smaller circle.

http://codepen.io/desandro/pen/1808c09e7dd2bf8e086b51d0421c329c

**Comment by amustill** [comment]
Thanks for the reply. I figured the tap listener was the cause and the reason why it may not work as expected.

Ultimately I used a similar CSS technique to the one you mentioned, but figured it was worth raising here as a discussion point for other devs who may hit the same problem.
