### ISSUE TITLE
asnavfor - multiply rows

### ISSUE THREAD

**Issue by Track77** [metafizzy/flickity#532]
If it possible to create multiply row with  'asnavfor' option?
http://flickity.metafizzy.co/options.html#asnavfor

Thanks!

**Comment by desandro** [comment]
Thanks for submitting this issue. Could you elaborate on what you're looking for? It sounds like you'd want a custom kind of navigation where instead of a Flickity carousel, you want to show multiple thumbnails, that could be displayed in multiple rows. Is that right? If so, take a look at the [custom nav example](http://flickity.metafizzy.co/extras.html#custom-navigation-ui)

**Comment by Track77** [comment]
Thanks - it's look like  solution!
