### ISSUE TITLE
flexbox layout - no need for position absolute

### ISSUE THREAD

**Issue by tobz-nz** [metafizzy/flickity#564]
I think a whole bunch of issues could be results of the slide/cells where not positioned absolutely and instead flexbox used for layout.
Everything would use the native document flow.

I've just done a little hack in dev tools & it seems to work. If this is something you'd be interested in doing, I'd be more than happy to do the work & PR it - its pretty simple.

- change slider's `display: absolute` -> `display: relative`
- remove `position: absolute` from cells
- add `display: flex` to the slider
- remove `left` from cells. 

That's about it I think.

Thoughts?

**Comment by desandro** [comment]
Thanks for this suggestion! I believe it may work when cells have `px`-based widths, but if cells have `%` widths, then it changes how their sizing works.

Compare [original half-width cells demo](http://codepen.io/desandro/pen/gbvOvy) with [flexbox half-width cells demo](https://codepen.io/desandro/pen/73dc01d4d9155d88468b26eb3aba71c1/). In the flex box demo, the cells are flex-sized down to fit in the slider. So this would require sizing up the slider element so all the elements could fit, but then `50%` would be a size of a bigger slider, and we'd get into a circular logic bug.

That's why Flickity uses all this absolute positioning, for those `%` cell sizes. It's not elegant on the implementation side, but I think it works well for users. That said, I'm open to exploring different layout solutions that could work better without absolute positioning.

**Comment by tobz-nz** [comment]
I've implemented this on my cirrent project & it works perfectly. It might be because all my cells are `100vw` wide, but I don't think so - pretty sure it'd work fine with different width cells.

The flex container (`.slider`) still has the correct dimensions - as long as you don't `flex-wrap` it.
If I get some time I'll write up a demo, or failing that post my implementation when its live.

**Comment by desandro** [comment]
There's also [wrapAround](https://flickity.metafizzy.co/options.html#wraparound) to consider. Having all items be `position: absolute` makes it easier to move them around for wrapAround behavior.

**Comment by tobz-nz** [comment]
the `order` css property could be used for that.

**Comment by kukac7** [comment]
@desandro your example does not work well.
here is good: https://codepen.io/kukac7/pen/WjVjOP
this is it?

**Comment by desandro** [comment]
@kukac7 Thanks for that demo. While it works, I'm not a fan of this CSS

``` css
.carousel-cell {
  flex: 0 0 50%;
  max-width: 50%;
  width: 100%;
}
```

It's hard to understand what exactly the size will be.

**Comment by kukac7** [comment]
@desandro 50% because of flexbox.

**Comment by tobz-nz** [comment]
Wouldn't just using the natural content width be the desired effect?
```
.carousel-cell {
    flex: 0 0 auto;
}
```

**Comment by cdthorpe** [comment]
Along with the following CSS, set "resize" to false on plugin init. Please note, there's a lingering visual flicker between first/last cells.

.flickity-enabled {
    display: flex;
}

.flickity-viewport {
    order: 2;
    width: 100%;
    height: auto !important;
}

.flickity-slider {
    position: relative !important;
    display: flex;
    left: auto !important;
}

.carousel__cell {
    flex: 0 0 auto;
    flex-direction: row;
    left: auto !important;
    max-width: 100%;
    min-height: 100%;
    position: relative !important;
    width: 100%;
}

.flickity-prev-next-button {
    align-self: center;
    position: relative;
}

.flickity-prev-next-button.previous {
    order: 1;
    left: auto;
}

.flickity-prev-next-button.next {
    order: 3;
    right: auto;
}

**Comment by desandro** [comment]
Thank you for for your input on this one. Alas, I have decided to pass on this feature. 🐳

**Comment by tomanatura** [comment]
Is there solution for  flexbox X wrapAround?
