### ISSUE TITLE
Option to start Flickity on load event

### ISSUE THREAD

**Issue by vaidotas-adf** [metafizzy/flickity#602]
When initializing Flickity using "data-flickity" attribute, it starts on DOMContentLoaded event. In some cases it is better to wait for all assets to load (e.g. when using responsive images) and only then initialize Flickity. That way there's no need for additional resize call after load.
Maybe additional data-flickity attribute could be added, that would start Flickity on load event?

**Test case:** https://codepen.io/anon/pen/dRxGEK

**Comment by desandro** [comment]
Thanks for submitting this issue. If you would prefer to load Flickity on `window.load`, then I recommend you [initialize in JavaScript](https://flickity.metafizzy.co/#initialize-with-jquery) rather than with HTML  & `data-flickity`.

``` js
// jQuery
$( window ).load( function() {
  $('.carousel').flickity({...});
});
```

``` js
// vanilla JS
window.addEventListener( 'load', function() {
  new Flickity( '.carousel', {...});
});
```

Be sure to remove the `data-flickity` attribute so you Flickity instance only gets initialized once.
