### ISSUE TITLE
[Bug report] position issue when resizing with wrapAround slides inside relative width parent

### ISSUE THREAD

**Issue by yaodingyd** [metafizzy/flickity#610]
**Test case:** https://codepen.io/earthmount/pen/MvymeQ

There are 4 slides, with `box-sizing: border-border`, each slide is 25% wide, and container is 80% wide.  Flickity is initialized with `"groupCells": "true", "wrapAround": "true"`. There are 2 issues observed:
1. all slides are not in view with initial load. ( each slide is 25%, so we should see all of them )
2. when resizing window, the first and last slides keep change position, thus keep showing and hiding.

A couple of conditions need to be met for this bug, if the parent is fixed width, or it's not wrapAround, then carousel works fine.

Thank you!

**Comment by desandro** [comment]
Thanks for reporting this issue! Looks like this bug is being caused by the scroll bar, which is present before Flickity is initialized. You can resolve it by adding

``` css
body { overflow-y: scroll; }
```

See demo https://codepen.io/desandro/pen/c474137e5a8ff81a5d43fad1d5f863ca/

As for the `wrapAround` bug, I feel this is related to #40. `wrapAround` should not be enabled if there's not enough content to cover it. I'll resolve that issue over there.

**Comment by yaodingyd** [comment]
Thanks! The first issue is fixed perfectly.
