### ISSUE TITLE
Animate Cell with multiple elements

### ISSUE THREAD

**Issue by CarlosUvaSilva** [metafizzy/flickity#621]
i have a cell with 3 photos. is it possible to add custom animations like expand width with CSS when i click go to next slide?

ideally i want something like this: http://www.annamorosini.it/en/

or at least shrink my photos from 100% width to 0% and then change slide. i tried jQuery onClick to no avail

**Comment by yaodingyd** [comment]
I created a pen [https://codepen.io/earthmount/pen/eEKMwy](https://codepen.io/earthmount/pen/eEKMwy) to showcase your expected effect.

Basically you need to have absolute positioned divs inside cell and  utilize events to manipulate them. You cannot animate cells directly because flickty needs it's fixed width to move between them.

**Comment by desandro** [comment]
You can add your own custom animation on Flickity's `select` event. That's how this fancy example was built: https://codepen.io/desandro/full/jEpxqJ
