### ISSUE TITLE
Feature request: ease for slide change transition

### ISSUE THREAD

**Issue by devsoft91** [metafizzy/flickity#634]
The animation about the slide change is too fast at the beginning and end depending on `friction` and `selectedAttraction` attribute it slow down at the end.
Should be great if there was the possibility to set an ease property in order to e able to slow down also the start of the slides animation.

Thanks!

**Comment by desandro** [comment]
Thanks for this feature request. Because Flickity is built on top of a physics model for its animation, I'm afraid adding easing functions would be overly complex. The `friction` and `selectedAttraction` are the next best solution. Sorry, but I'll have to turn this one down. All the same, thank you for your feedback 🌈🐻
