### ISSUE TITLE
Calculation drift when width constrained - animation stutter 

### ISSUE THREAD

**Issue by drewm** [metafizzy/flickity#655]
When the width of a carousel is constrained by its container to a proportional value (e.g. `vw` or `%`) something is drifting in the calculation for the end position of each cell.

The result is when transitioning the animation moves smoothly and then 'snaps' or 'jumps' the last few pixels to the correct end position. The distance of this jump increases with each cell, and is most visible from about 20 cells into a carousel. (Depending on width.)

This behaviour is present in Chrome 61 and Canary 64, but not in Safari or Firefox.

**Test case:** https://codepen.io/drewm/pen/aVwzVE

For the test case, I've forked the 'outside arrow style' demo and added a `div` to wrap the carousel. I've constrained the wrapper to `width: 90vw;` and then centred it in the viewport using `margin: 0 auto;`. The setting of the width triggers the issue.

I've added more cells to the carousel, as the issue is noticeable from typically about 20 cells in.

I'm running carousels with sometimes 150+ cells, so the jump becomes very jarring after a while!

**Comment by desandro** [comment]
Thanks for reporting this issue. This looks to be a browser rendering bug in Chrome caused by a difference between 2d rendering with `translateX` and 3d rendering with `translate3d`. I found a hack solution. Add this code before you initialized Flickity:

``` js
var transformProperty = ( function () {
  var style = document.documentElement.style;
  if ( typeof style.transform == 'string' ) {
    return 'transform';
  }
  return 'WebkitTransform';
})();

Flickity.prototype.positionSlider = function() {
  var x = this.x;
  // wrap position around
  if ( this.options.wrapAround && this.cells.length > 1 ) {
    x = utils.modulo( x, this.slideableWidth );
    x = x - this.slideableWidth;
    this.shiftWrapCells( x );
  }

  x = x + this.cursorPosition;
  // reverse if right-to-left and using transform
  x = this.options.rightToLeft && transformProperty ? -x : x;
  var value = this.getPositionValue( x );
  // use 3D tranforms for hardware acceleration on iOS
  // but use 2D when settled, for better font-rendering
  this.slider.style[ transformProperty ] = 'translateX(' + value + ')';

  // scroll event
  var firstSlide = this.slides[0];
  if ( firstSlide ) {
    var positionX = -this.x - firstSlide.target;
    var progress = positionX / this.slidesWidth;
    this.dispatchEvent( 'scroll', null, [ progress, positionX ] );
  }
};
```

See demo https://codepen.io/desandro/pen/c7976d56e1c4147d1d004560141e74f0/

> I'm running carousels with sometimes 150+ cells

That's a lot of cells and I'm frankly impressed that Flickity works at all. Honestly, with that much content you may be better off with another scaled-back solution like just using `overflow-x: scroll`.

**Comment by drewm** [comment]
The solution seems to work for me - thank you!

> That's a lot of cells and I'm frankly impressed that Flickity works at all.

It works flawlessly (save for the above issue). Doesn't feel sluggish and doesn't appear to unnecessarily tax the browser. Obviously I'll monitor it, but for now it's great. Thanks again.

**Comment by kapouer** [comment]
I'm having a similar issue w.r.t. transform2D / 3D difference of position in chrome.
- my setup is width 100%, cellWidth 25%, and a dozen cells to scroll. Before scrolling, the background can be seen as thin (white in that case) vertical lines between cells.
- i'm using percentPosition: true because otherwise there's a 1px gap at the beginning of the scroll

After a bit of testing, i figured transform2D was doomed.
I tried to move everything to transform3D but i have some texts and other transforms inside the cells... so it fails.
So i did this: https://github.com/pageboard/flickity/commit/557da99b3e83331692e0e4b7ee40f42f6a0eba4e
and the result is pretty good position-wise.

**Comment by MezMerrit** [comment]
I had a similar issue with the latest versions of Edge and Internet Explorer. I was dynamically adding 76 slides (SVGs) on load and everything went sluggish/jittery after they were added. I had a little giggle when I read desandro's comment "I'm frankly impressed that Flickity works at all" :D

I resolved the issue in a number of ways, but the one that had the most impact was paginating. I'm still loading 76 slides, but into an array instead of the DOM.

So now, the most that is loaded into the DOM at any given pagination-click is 24 slides. IE still leaves 1px behind when the settled event has completed, but it is sliding smoothly now. Firefox and Chrome didn't even hiccup to start with, so they're just super smooth and fast now. 

I also ditched as many $.each() loops as possible, in favour of standard javascript for loops, with noticable improvement.

And I referenced as much as possible by ID, rather than classes, so DOM searches weren't so intensive.

In the end, not only did I improve animation performance, but I also reduced the (local) load-time in Edge and Internet Explorer from 10 seconds to 4!! And hardly a blink between pagination-clicks.

Not that anybody cares much about IE users anymore... but my users are schoolie parents so I do have put some effort into IE.

Anyhoo, hope this helps someone out there with performance issues. 

Have a nice Day Folks!
