### ISSUE TITLE
Gap / margin between cells on initial load, until page resized

### ISSUE THREAD

**Issue by functionandform** [metafizzy/flickity#662]
Test case: https://codepen.io/toddpadwick/pen/yPxZOg

I can't seem to figure out where that space in between the slides is coming from. I have removed all margin from the slide. It seems to only disappear when re-calculated on window re-size.
Can you tell me how to fix this?

cheers

**Comment by Seonic** [comment]
```css
.flickity-viewport {
  position: relative;
}
```
Use flickity.css and in your code, after flickity init, div will be a child of ul, it's not valid, better change ul > li to div > div

**Comment by desandro** [comment]
Looks like the issue is that default padding around `ul` is throwing off the measurements. Plus, there may be a different in window width due to the scroll bar before Flickity is initialized. You can resolve both with this CSS:

``` js
html {
	overflow-y: scroll;
}

.quicklinks {
	position: relative;
	padding: 0;
}
```

See demo https://codepen.io/desandro/pen/9cb591e183021baa35a4ed33b70ce935
