### ISSUE TITLE
Lazyloaded images don't initially appear when new cells are added

### ISSUE THREAD

**Issue by isherwood** [metafizzy/flickity#675]
Cells prepended or appended while using lazyLoad don't load images until some navigation occurs. [Here's a demo](https://codepen.io/isherwood/pen/ypjzVN
). After 1500ms a cell is appended. Use the controls to navigate and the image will load (possibly due to the offset config it may take two clicks). 

In my application I append cells and do not want to programmatically navigate the slider. Is there some other way I can trigger image loading for newly-created slides in the viewport?

**Comment by desandro** [comment]
> Is there some other way I can trigger image loading for newly-created slides in the viewport?

Not exactly. There is no API to trigger lazy-loading on specific cells.

However, There is an undocumented method `lazyLoad`. This method is called on `select`, which is why newly appended cells may not trigger it until a new cell is selected.

For your demo, you can trigger `lazyLoad` after `append`. 

``` js
    slider.flickity('append', element);
    slider.flickity('lazyLoad');
```

For your demo, because the newly appended cell is 3 away from the first, selected cell, you'll have to set `lazyLoad: 3` in options.

See demo https://codepen.io/desandro/pen/7fd9180e44a5dccfdeaf7d1dc0ba246f/

**Comment by isherwood** [comment]
Thank you. That seems like a viable solution. Unfortunately it seems to have no effect in my app. I see the function being called, but the DOM isn't updated. I'll keep investigating.
