### ISSUE TITLE
Question: why the use of <ol> for dotted navigation?

### ISSUE THREAD

**Issue by camilodelvasto** [metafizzy/flickity#676]
Thanks for the awesome product. This is not a bug, but rather a question.
Here's the markup produced by the 'dotted navigation':
```html
<ol class="flickity-page-dots">
  <li class="dot"></li>
  <li class="dot is-selected">
  </li><li class="dot">
</ol>
```
I'm wondering: is it needed to have a numbered list? is there an option for using a <ul> tag instead? Seems like a weird choice, but thanks for your help!

**Comment by desandro** [comment]
Hi! Good question. I decided to use `ol` because it's for an ordered list. The list goes 1,2,3 that matches the number of slides. The `li` tags themselves are empty, so it may not be a perfect example.

Sorry, no there is no option to use another element. You would have to fork the project and change the source code.

**Comment by camilodelvasto** [comment]
Got it, maybe I try it! :)
