### ISSUE TITLE
Animation Bug with Lazyload and wrapAround

### ISSUE THREAD

**Issue by jordan-realfoto** [metafizzy/flickity#688]
If you immediately slide click to the left the slide animation happens twice. It only happens the first time the slide is encountered, maybe because flickity tagsthe slide once it becomes the active index the first time.

**Test case:** https://codepen.io/jdogg/pen/zRBRzG

**Comment by desandro** [comment]
Thanks for reporting this issue. I'll have to take a look.

**Comment by desandro** [comment]
The cause of this issue is likely related to how the cells are sized. The cells have no size set in CSS. So they fall back to the size of the image. When the image is loaded, Flickity has to reposition its slider to account for the new sizes.

The best solution is to set a size for cells. See lazyLoad example https://codepen.io/desandro/pen/vOeGzL

**Comment by jordan-realfoto** [comment]
@desandro of course that makes complete sense. thanks for the response!
