### ISSUE TITLE
The sliders are not pre-composited

### ISSUE THREAD

**Issue by ivancuric** [metafizzy/flickity#7]
The sliders are only composited when they begin to move potentially causing some input lag. Have you thought about applying a `will-change: transform`, or a `backface-visibility: hidden` to force layer compositing?

**Comment by desandro** [comment]
Thanks for this suggestion. In my experience, adding compositing before interaction comes with a trade-off: disables sub-pixel font anti-aliasing on some platforms, and potential sub-pixel positioning that making rendering look blurry. That's why compositing only happens when the user starts dragging.

`will-change: transform` may be a good compromise. I'll have to look into this.

---

If [you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), email me yo@metafizzy.co and I'll send some your way!

**Comment by ivancuric** [comment]
`will-change: transform` does cause text blurring as well under some conditions.
However, since the lag is mostly noticable when flick scrolling on touch devices, which luckily only use grayscale rendering + high DPI, I made the following tweak:
```scss
.flickity-slider {
  position: absolute;
  width: 100%;
  height: 100%;
  .touch & {
    will-change: transform;
  }
}
```
In combination with modernizr, it greatly improved the response time on my Nexus 5 running chrome 41 on android 5.1.

**Comment by desandro** [comment]
Thanks for the report!

**Comment by desandro** [comment]
I've decided to not implement this feature.
