### ISSUE TITLE
Flickity next/previous functions are undefined

### ISSUE THREAD

**Issue by mariyanang** [metafizzy/flickity#74]
When I create a new flickity instance:

        var flkty = new Flickity($sliderCont.get(0), {
          cellAlign: 'center',
          cellSelector: '.touchslider-item',
          wrapAround: false,
          initialIndex: 1,
          prevNextButtons: true,
          setGallerySize: true,
          pageDots: false,
          resize: false
        });

And then log `console.log(flkty);` I see the following:

        _events: Object
        accel: 0
        cellAlign: 0.5
        cells: Array[3]
        cursorPosition: 182.5
        element: div#touchslider-products-cont.flickity-enabled.is-draggable
        guid: 1
        handles: Array[1]
        isActive: true
        isAnimating: false
        isDragBound: true
        maxCellHeight: 449
        nextButton: PrevNextButton
        options: Object
        originSide: "left"
        player: Player
        prevButton: PrevNextButton
        restingFrames: 3
        selectedCell: Cell
        selectedElement: div.touchslider-item.is-selected
        selectedIndex: 1
        size: Object
        slideableWidth: 480
        slider: div.flickity-slider
        velocity: 0
        viewport: div.flickity-viewport
        x: -240
        __proto__: Flickity

Therefore, I cannot call functions mentioned in the API reference such as `flkty.previous` and `flkty.next`.

Am I missing something?

**Comment by desandro** [comment]
`next` and `previous` are not listed in `console.log` because they are part of `Flickity.prototype`. If you expand `__proto__`, you'll find both methods in there, along with all other Flickity prototype methods.

If you're having trouble with previous/next, could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by mariyanang** [comment]
Thanks for the quick reply.You're right about the prototype (i'm still learning javascript). At least now I know i should look elsewhere to fix my problem. Awesome slider btw, cheers!
