### ISSUE TITLE
Custom dot navigation, select first dot on 'ready'

### ISSUE THREAD

**Issue by kaleidografik** [metafizzy/flickity#749]
Hi, I've followed the custom dot navigation in the 'extras' section of the Flickity site, but cannot seem to be able to set 'is-selected' on the first dot when Flickity is ready. It seems I am not able to detect when Flickity is ready. In the code below, how can I adjust to ensure the first dot has the .is-selected class upon load/ready?

Thanks!

```
// Hero carousel
var $heroCarousel = $('.hero-feature-carousel').flickity({
	// Options
	cellAlign: 'left',
	groupCells: 1,
	imagesLoaded: true,
	lazyLoad: 2,
	prevNextButtons: false,
	pageDots: false,
	contain: true
});

	// Create custom bullet navigation to enable more flexible positioning
	var flkty = $heroCarousel.data('flickity');

	// Elements
	var $cellBulletNavigation = $('.custom-bullet-navigation');
	var $cellBullets = $cellBulletNavigation.find('.bullet');

	// Update selected cellBullets
	$heroCarousel.on( 'select.flickity', function() {
		$cellBullets.filter('.is-selected')
			.removeClass('is-selected');
		$cellBullets.eq( flkty.selectedIndex )
			.addClass('is-selected');
	});

	// Select cell on button click
	$cellBulletNavigation.on( 'click', '.bullet', function() {
		var index = $(this).index();
		$heroCarousel.flickity( 'select', index );
	});
```

**Comment by desandro** [comment]
If the first cell is always going to be the initial selected cell, the simplest solution is to add `is-selected` to the custom dot in HTML. That's the solution used in the demo: https://codepen.io/desandro/pen/jEZwxb

Otherwise, if you can use [Flickity's `ready` event](https://flickity.metafizzy.co/events.html#ready)

**Comment by kaleidografik** [comment]
@desandro - thanks for the reply. I'm not able to set the class in the HTML as the number of slides and dots is auto generated as part of a Wordpress loop. I have tried to implement the ready event in the above code but for some reason it does not register, even to output a console log. Could you please adjust the supplied code to use ready to add the class to the first dot? Thanks in advance.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by creativezest2021** [comment]
I'm using flickity with two carousels and one set of custom controls that control both synced carousels. 

However, although it is possible to drag/swipe both carousels, it is only the top one that affects the active state of the controls, the bottom one does not. 

Additionally, when dragging or swiping, the carousels aren't synced, so that if I drag/swipe the bottom one, the top one doesn't move in accordance. 

Is there any way to achieve both of the above? 

Thanks in advance.

**Comment by desandro** [comment]
@creativezest2021 See [flickity-sync](https://github.com/metafizzy/flickity-sync)
