### ISSUE TITLE
Already using imagesLoaded and Masonry

### ISSUE THREAD

**Issue by justnorris** [metafizzy/flickity#75]
Hi Desandro,
You're reusing lots of code between your awesome stuff, but that also means that I have redundant code redundant code in my compiled libs.js file file. 

I'm using imagesLoaded, Masonry and now Flickity too. Is there a suggested way that I import all of the plugins with their dependencies ?

**Comment by desandro** [comment]
Good question! If you're looking to immediately use Masonry, imagesLoaded, or Flickity, then using a `.pkgd.js` file is the way to go. It's on simple file that has everything you need.

Once you start building larger sites with multiple components, I recommend looking into package management, with npm or Bower. Then you can hook it into frameworks like [Browserify](http://browserify.org/), [RequireJS](http://requirejs.org/), or perhaps your own custom build scripts in [Gulp](http://gulpjs.com/) and [Grunt](http://gruntjs.com/).

Package management will resolve the duplicates, so that your compiled code is clean. There are multiple ways to do it, so I try to be too opinionated about how to go about it. Flickity, Masonry, and imagesLoaded all have docs on how to use them with both Browserify and RequireJS.
