### ISSUE TITLE
Adding items causes jumping

### ISSUE THREAD

**Issue by W1zzardTPU** [metafizzy/flickity#751]
https://codepen.io/anon/pen/MGjKzo

Flick through the items one by one, note how the carousel jumps after the 3rd item
 (because now new items get added).

This is even more noticeable with freeScroll: true

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. Yes, this behavior is working as intended. When you add or remove a cell to a Flickity carousel, Flickity has to reposition all the cells. This is to account for changes with `wrapAround` or `groupCells`. I recommend using `settle` instead of `change` event, so the change happens when the carousel is not moving.  See demo https://codepen.io/desandro/pen/41764e649d89ceb51cd6c10e81683dc9/

**Comment by W1zzardTPU** [comment]
The idea is to load more items as the user is scrolling, so settle won't be useful.

Theoretically speaking, when appending items, there should be no reason why anything of this should be happening, right?

**Comment by W1zzardTPU** [comment]
and now it's working as intended, butter smooth:

```
var t=$carousel.find('.flickity-slider').css('transform');
$carousel.flickity('append', items);
$carousel.find('.flickity-slider').css('transform', t);
```
