### ISSUE TITLE
Flickity image positioning issue

### ISSUE THREAD

**Issue by endhillgames** [metafizzy/flickity#755]
I have a site with 3 'sections' which scroll in using jQuery animate. When I load the page with the Flickity section shown first, there's no issues. 

<img src="https://i.imgur.com/RSBVJG2.png">

When I load the page with a different section and change to the Flickity section, I get this:
<img src="https://i.imgur.com/U1uivpI.png">
(<a href="https://media.giphy.com/media/1d7EnYTUahwPIV3xX8/giphy.gif">gif of transition</a>)

It fixes itself when I resize the window. I've tried using $carousel.flickity('resize') but I don't think it's meant for this purpose

I know this is a very specific problem but I thought I'd give it a shot anyway. Looking forward to your response!

**Comment by desandro** [comment]
If the carousel is hidden and then revealed when transitioned, you may need to trigger [`resize` method](https://flickity.metafizzy.co/api.html#resize).

Otherwise, if you provide a **reduced test case**  I can better address this issue. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by endhillgames** [comment]
Triggering the resize method after revealing the carousel worked. Thanks again!
