### ISSUE TITLE
Flickity conflict with Facebook Customer Chat Plugin

### ISSUE THREAD

**Issue by AdamJaggard** [metafizzy/flickity#801]
I noticed a strange bug on a site I'm working on. [Facebook's Customer Chat Plugin](https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/) won't open or close properly on mobile if Flickity has also been initialised on the same page. This bug only appears on pages with Flickity in on mobile (see test case).

What I have noticed:
- On page load, if you don't scroll the page, the chat plugin opens and closes fine on tap
- After scrolling once, the chat plugin no longer opens on tap, will occasionally open on a longer press if timed right
- Behaviour doesn't manifest on pages without Flickity on
- Same behaviour after setting draggable: false in Flickity options

Reduced Test Case
- [With Flickity and bug](https://dodatenight.com/wp-content/themes/datenight/fb-flickity-test/index.html)
- [Without flickity and no bug](https://dodatenight.com/wp-content/themes/datenight/fb-flickity-test/without-flickity.html)

Currently only observed on iOS Safari (11.3.1). I will try and confirm if it's an issue on Android when I get access to a device.

I haven't had a proper dive into the Flickity source yet but guessing some event listeners are being removed somewhere after scrolling? I will have a look myself and see if I can identify where it's happening.

**Comment by desandro** [comment]
Thanks for reporting this issue. Given the complexity of the Facebook Customer Chat Plugin, this is going to difficult to debug. It could be related to #740 or #725. If others report a similar issue I can get better context for how prevalent this bug is.

> event listeners are being removed somewhere after scrolling?

Yes. See [`onscroll`](https://github.com/metafizzy/flickity/blob/v2.1.2/js/drag.js#L374) and [`_pointerDone`](https://github.com/metafizzy/unipointer/blob/master/unipointer.js#L242)

**Comment by Josecc** [comment]
Could probably narrow between the two if the device is Android(#725) or iPhone(#740)
