### ISSUE TITLE
tap-highlight-color invalid CSS

### ISSUE THREAD

**Issue by toplisek** [metafizzy/flickity#863]
I have validated CSS and found an error:
Line 4
.flickity-enabled.is-draggable | Property tap-highlight-color doesn't exist :                                                                                   transparent

Is this an error or validator reports the wrong message?
Validator:http://jigsaw.w3.org/css-validator/validator

**Comment by desandro** [comment]
Thanks for reporting this issue. This property was added as a way of future-proofing, in case future browsers adopted `tap-highlight-color`. Although it is technically not a valid property, its inclusion in the CSS will not affect the rendering or performance of your site.

**Comment by toplisek** [comment]
I understand but the compiler will not manage this task as validation shows an error.

**Comment by zvaehn** [comment]
i am currently also struggling with this and i dont want to make changes in our project version, because any flickity update will overwrite those changes.

Is there a way to use it only with the browser vendor prefix?

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Funpkg.com%2Fflickity%402%2Fdist%2Fflickity.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by desandro** [comment]
Flickity v2.2.1 has been released with `tap-highlight-color` removed. Please update!
