### ISSUE TITLE
flickity-slider has a transform: translateX that gives unwanted white space

### ISSUE THREAD

**Issue by tr1s** [metafizzy/flickity#902]
As you can see in the video, how come that's there and how do I make it go away? I assume messing with the transforms will break how flickity functions. 

[Here's a video showing the issue](https://www.dropbox.com/s/ink0h98cpfxbnk4/Screen%20Recording%202019-02-11%20at%202.06.15%20PM.mp4?dl=0).

My SCSS...

```sass
.pics-carousel {
  width: 100%;
  max-width: 100%;
  .pics {
    width: 100%;
    height: 100vh;
    object-fit: cover;
    display: block;
  }
}
```

**Comment by tr1s** [comment]
Also, it goes away when I open dev tools, but the moment I refresh it's back. Strange behaviour.

**Comment by desandro** [comment]
Could this be a scrollbar issue?

``` css
/* force scrollbar */
html { overflow-y: scroll; }
```

**Comment by daGUY** [comment]
I'm having the exact same issue and @desandro 's solution of forcing a vertical scrollbar fixes it.

I think this happens if the slider content is taller than the viewport without Flickity applied, but shorter than the viewport with it. When Flickity initializes, it determines the slide width based on the scrollbar being there, and so once the scrollbar disappears after the content is rearranged into a horizontal carousel, you end up with a gap. Opening the developer tools changes the width of the viewport, which forces Flickity to update the slide width, which is why that fixes it until you refresh.

Is there any way to fix this without having to force a vertical scrollbar?

**Comment by desandro** [comment]
Another solution is to trigger [`resize`](https://flickity.metafizzy.co/api.html#resize) on [`ready`](https://flickity.metafizzy.co/events.html#ready)

``` js
$carousel.on( 'ready.flickity', function() {
  $carousel.flickity('resize');
});
```

**Comment by banago** [comment]
For people running on the same issue, that's the default behavior and not a bug, where it centers the first cell. To make the first cell go to the edge use these options:

    {
        contain: true,
        groupCells: true
    }
