### ISSUE TITLE
Allow swiping only to the next/previous cell

### ISSUE THREAD

**Issue by permanyer** [metafizzy/flickity#91]
Touch sliding slides an arbitrary number of cells (i expect to slide only one cell per touch event).
Do you know what it is due to?
I am thinking of leaving it with freescoll = true, but that is not what i wanted

My configuration is:

```
var $gallery = $('.carousel-outside').flickity({
      prevNextButtons: false,
      pageDots: false,
      wrapAround: true,
      resize: false,
      initialIndex: _initialIndex
    });
```

and site is concertsperanadons.cat

**Comment by desandro** [comment]
I'm having trouble understanding your issue. Can you explain what the expected behavior is, and what the current behavior you are seeing? 

It sounds like you only want to slide 1 cell per each swipe. Flickity's behavior allows users to slide past cells, and flick further based on the speed of the flick. Do you want to limit this behavior?

**Comment by permanyer** [comment]
Sorry, I explained myself badly.
Yes, exactly, i just want to slide only one cell per flick.

In desktop mode, by dragging the slider, i achieve OK the behaviour i want. But in touch devices, depending on the flick, a lot of cells pass by and i do not know when it is going to stop.

So, yes, is it possible to limit it to one cell slide, no matter the speed/strength of the flick?

**Comment by permanyer** [comment]
Hello
Just as a reminder:
Is it possible to have 1 cell slide per each swipe?

**Comment by permanyer** [comment]
Hi, i found the friction param.
Now i am sticking with
'''
var _touch = $('html').hasClass('no-touch') ? false :true;
	// init Flickity
	var $gallery = $('.carousel-outside').flickity({
	  prevNextButtons: false,
	  pageDots: false,
	  wrapAround: true,
	  resize: true,
	  initialIndex: _initialIndex,
	  //freeScroll: _touch,
	  //draggable: !_touch
	  friction: _touch ? .6 : .2
	});
'''
which is more or less OK if you want lo limit to 1 cell slide per swipe

**Comment by desandro** [comment]
Yes, adjusting friction is one way to handle it. I'm changing this issue to a feature request.

I feel it's a better user experience to allow users to flick/swipe to further cells. Locking them in to one cell at a time feels limiting.

**+1** this issue if you would like to see this feature implemented.

**Comment by permanyer** [comment]
+1

Thanks for your support :) !!

**Comment by pesla** [comment]
+1

**Comment by saunders1989** [comment]
+1

**Comment by drastick** [comment]
+1 

I'm confused by the amount of features that are limited based on personal opinion. Shouldn't it be left to the person implementing it to decide what is best for their users?

**Comment by desandro** [comment]
@drastick My opinion is comprised of multiple factors.

1. Does this feature provide considerable value to users? (a little)
2. How much demand for this feature with developers? (a little)
3. How much complexity will adding this feature add to the project? (a good amount)
4. Do I like this feature? (not really)

I'm not just considering this one feature, but how it affects the whole project and its end-to-end experience. This project, Flickity, has [20+ open feature requests](https://github.com/metafizzy/flickity/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) and it's only been around for a couple months. Being opinionated about which features do and do not get added is good for the health of the project.

> If all you do is react to current needs and expressed demands, you will initiate a "customer-driven death spiral." Don't follow the victim.

— [Alan Cooper](https://twitter.com/MrAlanCooper/status/594522819943268352)

**Comment by drastick** [comment]
@desandro I don't disagree that you shouldn't react to everyones whims nor do I believe that all features should be implemented just to say that they are there.  I do however feel that core features that other carousels have, and that people are used to, should be strongly considered and voted on to exclude rather than include.

  1. Does this feature provide considerable value to users? - This is the typical behavior on many mainstream sites that utilize carousels ([aol](http://www.aol.com), [yahoo](http://www.yahoo.com)).  So from a user experience perspective this is what the user will be comfortable with.  The flickity implementation goes against the norm. Also based on my testing the friction is pretty finicky on tablet and phone (both iOS) such that it will jump multiple slides in an unpredictable manner.  Ex. The same perceived force on one 'flick' will jump 2 slides one time and 4-5 the next.
  2. How much demand for this feature with developers? - 4 People in a month that care enough to look through issues and +1 a request is a decent number.
  3. How much complexity will adding this feature add to the project? - Seems like the physics could use some tweaking anyway regardless of if you like this feature. (see #1)
  4. Do I like this feature? - *shrug*

**Comment by permanyer** [comment]
Sorry to drop in, but we are requesting the default behavior of all touch devices when it comes to swiping pictures since ever. You always swipe one at a time. Carousels are quite often used as image galleries, imho

I think a swipe gesture should be the same as an arrow click in a default behavior. After that, you could customize things to do fancier things, don't you think the same?

**Comment by timkirtley** [comment]
+1

increasing friction helps reduce flicking through multiple slides, but if you drag the carousel along from one edge of the device to another I'm still able to advance forward more than one slide - would be nice to guarantee that cant happen via an option.

**Comment by jgerigmeyer** [comment]
+1

**Comment by arkid** [comment]
+1   agree completely with drastick.   Right now for example I'm trying to use two instances of the plugin on one page that shows a "gallery" of photos.   What I have is a large top instance of Flickity that I want to use to show a single image at a time.  Below that I want a sliding thumbnail scroll of all the images within the "gallery".   Being able to make flickity show just one image at a time would make it so much more flexible.

**Comment by LBKinson** [comment]
+1

**Comment by kaiserkiwi** [comment]
+1

**Comment by harrisdavid** [comment]
incase this helps anyone, I set up a swipe limit in the drag code - added a drag width setting
`
Flickity.defaults = {
  accessibility: true,
  // adaptiveHeight: false,
  cellAlign: 'center',
  // cellSelector: undefined,
  // contain: false,
  freeScrollFriction: 0.075, // friction when free-scrolling
  friction: 0.28, // friction when selecting
  namespaceJQueryEvents: true,
  // initialIndex: 0,
  percentPosition: true,
  resize: true,
  maxSwipeWidth: 2, // !dh hmm added - this controls number of slide widths swipable
  selectedAttraction: 0.025,
  setGallerySize: true
  // watchCSS: false,
  // wrapAround: false
};
`

and then in the proto.dragMove = function( I added a limiter...

` 
  if( Math.abs(this.dragStartPosition - dragX) > this.size.width * this.options.maxSwipeWidth  ){
	dragX = this.previousDragX;
  }
  this.dragX = dragX;
`

**Comment by desandro** [comment]
I have ultimately decided not to add this feature. It was a valid request, but I'm prioritizing other more popular feature requests. Thanks again for submitting this suggestion.
