### ISSUE TITLE
Click events on the prev/next buttons

### ISSUE THREAD

**Issue by Neve12ende12** [metafizzy/flickity#919]
Click functions attached to the next/previous buttons don't fire when scrolling to the first and last slide.

https://codepen.io/anon/pen/VRyBaj?editors=1111

**Comment by desandro** [comment]
Thanks for reporting this issue. The click does not fire. because the button is `disabled` by Flickity. This is by design, for both API & accessibility. If you need a button that dispatches click events, you may be better off building your own [custom nav UI](https://flickity.metafizzy.co/extras.html#custom-navigation-ui).
