### ISSUE TITLE
Choosing where to append arrows & dots

### ISSUE THREAD

**Issue by dennispw** [metafizzy/flickity#944]
Is it possible to choose where the arrows and dots are appended? I know we currently have the option of creating [custom ones](https://flickity.metafizzy.co/extras.html#custom-navigation-ui) but having an option to target a selector to append these would be great. Perhaps something like:

```javascript
var flkty = new Flickity( elem, {
  prevNextButtonsTarget: '.foo',
  pageDotsTarget: '.bar'
});
```

What are the chances of having something like this added?

**Comment by desandro** [comment]
> What are the chances of having something like this added?

Eh, not good :) Rather than adding another couple of options, I think the better technique is to create your own [custom navigation UI](https://flickity.metafizzy.co/extras.html#custom-navigation-ui) using the Flickity API. This way you can have full control over where and how the nav works. I've created demos for both [jQuery](https://codepen.io/desandro/pen/jEZwxb) and [vanilla JS](https://codepen.io/desandro/pen/emVRjv)

**Comment by j-masci** [comment]
Seems like it would be really nice to have the option. I'm not sure if I can use the data-flickity attribute with your vanilla JS, ie. where to I get the flickity instance for the slider. Also seems like they should just be in their own container by default but are just appended to the slider. I'm new to flickity and only working on someone else's code, so forgive me if I have a poor understanding of how things work. I was hoping I could solve this in 5 minutes but its taken a lot longer so far. Other sliders I've worked with did not have this issue.

**Comment by j-masci** [comment]
If you would consider accepting a pull request for this please let me know. Thanks.
