### ISSUE TITLE
flickity is not responsive

### ISSUE THREAD

**Issue by neoman666** [metafizzy/flickity#991]
Is it possible to give flickity a responsive behavior for images. With responsive behavior I mean it like bootstrap 4. There is the class img-fluid. If I use the class img-fluid in my pictures at flickity, flickity will not work anymore.

Here is a [codepen](https://codepen.io/neoman666/pen/MWWjxgM).

**Comment by neoman666** [comment]
Could solve the problem through [here](https://codepen.io/desandro/pen/d06252fe9e7b427f5846fd1e47604464/).

**Comment by cheeseytoastie** [comment]
I've had head scratching moments with this. It's basically due to the fact the image hasn't loaded when Flickity inits and your div hasn't got the required height (as the image is what is giving your div height). 

If you don't want to set the height of the carousel cell to keep it flexible, either set imagesLoaded: true to make Flickity wait for the images or I put some responsive padding on the div to pad it out and position the images absolutely to each cell. 

Well that's the way I've been handling it but I bow to others knowledge on this.
